### ISSUE TITLE
TypeError: data.readUIntBE is not a function     at EBMLDecoder.readContent (EBMLDecoder.js:215:1)

### ISSUE THREAD

**Issue by onthegit** [legokichi/ts-ebml#52]
Hello, testing this library in react project (v17). The error that occurs is :
TypeError: data.readUIntBE is not a function
    at EBMLDecoder.readContent (EBMLDecoder.js:215:1)

Tried : 
```
'ebml': path.resolve(__dirname, 'node_modules/ebml/lib/ebml.esm.js'),
    'buffer':path.resolve(__dirname, 'node_modules/buffer/index.js'),
```

in webpack config. But it does not to work. Any other solutions?

**Comment by onthegit** [comment]
Solved with rewiring the react webpack config and adding plugin for buffer.
